export const courierList = [
  {
    key: "shopee-express",
    name: "ช้อปปี้ เอ็กซ์เพรส",
    color: "#F14613",
    imageURL: "https://fast.etrackings.com/courier/shopee-express.jpg",
  },
  {
    key: "kerry-express",
    name: "เคอรี่ เอ็กซ์เพรส",
    color: "#FB8523",
    imageURL: "https://fast.etrackings.com/courier/kerry-express.jpg",
  },
  {
    key: "flash-express",
    name: "แฟลช เอ็กซ์เพรส",
    color: "#FFD21A",
    imageURL: "https://fast.etrackings.com/courier/flash-express.png",
  },
  {
    key: "inter-express",
    name: "อินเตอร์ เอ็กซ์เพรส",
    color: "#027FDB",
    imageURL: "https://fast.etrackings.com/courier/inter-express.jpg",
  },
  {
    key: "cj-logistics",
    name: "ซีเจ โลจิสติกส์",
    color: "#F5B900",
    imageURL: "https://fast.etrackings.com/courier/cj-logistics.jpg",
  },

  {
    key: "jt-express",
    name: "เจแอนด์ที เอ็กซ์เพรส",
    color: "#FE1B3A",
    imageURL: "https://fast.etrackings.com/courier/jt-express.jpg",
  },

  {
    key: "ninja-van",
    name: "นินจาแวน",
    color: "#D50037",
    imageURL: "https://fast.etrackings.com/courier/ninja-van.png",
  },
  {
    key: "best-express",
    name: "เบสท์ เอ็กซ์เพรส",
    color: "#F70958",
    imageURL: "https://fast.etrackings.com/courier/best-express.jpg",
  },
  {
    key: "global-cainiao",
    name: "Global Cainiao",
    color: "#FA123C",
    imageURL: "https://fast.etrackings.com/courier/global-cainiao.png",
  },
  {
    key: "dhl-ecommerce",
    name: "ดีเอชแอล อีคอมเมิร์ซ",
    color: "#F5BA00",
    imageURL: "https://fast.etrackings.com/courier/dhl-ecommerce.png",
  },
  {
    key: "aramex",
    name: "อาราเม็กซ์",
    color: "#FF2E2B",
    imageURL: "https://fast.etrackings.com/courier/aramex.png",
  },
  {
    key: "nim-express",
    name: "นิ่ม เอ็กซ์เพรส",
    color: "#02D7C5",
    imageURL: "https://fast.etrackings.com/courier/nim-express.png",
  },
  {
    key: "scg-express",
    name: "เอสซีจี เอ็กซ์เพรส",
    color: "#F5370D",
    imageURL: "https://fast.etrackings.com/courier/scg-express.png",
  },
  {
    key: "speed-d",
    name: "สปีด-ดี",
    color: "#0B92EC",
    imageURL: "https://fast.etrackings.com/courier/speed-d.jpg",
  },
  {
    key: "business-idea-transport",
    name: "บิสซิเนส ไอเดีย ทรานสปอร์ต",
    color: "#00BC80",
    imageURL: "https://fast.etrackings.com/courier/business-idea-transport.png",
  },
  {
    key: "dhl-express",
    name: "ดีเอชแอล เอ็กซ์เพรส",
    color: "#F2E200",
    imageURL: "https://fast.etrackings.com/courier/dhl-express.png",
  },
  {
    key: "bee-express",
    name: "บี เอ็กซ์เพรส",
    color: "#F99F39",
    imageURL: "https://fast.etrackings.com/courier/bee-express.png",
  },

  {
    key: "ups",
    name: "ยูพีเอส",
    color: "#F9D523",
    imageURL: "https://fast.etrackings.com/courier/ups.png",
  },
  {
    key: "acommerce",
    name: "เอคอมเมิร์ซ",
    color: "#11DC76",
    imageURL: "https://fast.etrackings.com/courier/acommerce.png",
  },
  {
    key: "ems-international",
    name: "EMS International",
    color: "#0856FD",
    imageURL: "https://fast.etrackings.com/courier/ems-international.png",
  },
  {
    key: "china-post",
    name: "ไชน่า โพสต์",
    color: "#00A854",
    imageURL: "https://fast.etrackings.com/courier/china-post.png",
  },
  {
    key: "por-lor-express",
    name: "ปอลอ เอ็กซ์เพรส",
    color: "#2C4FFF",
    imageURL: "https://fast.etrackings.com/courier/por-lor-express.jpg",
  },
  {
    key: "fed-ex",
    name: "เฟดเอกซ์",
    color: "#6112FF",
    imageURL: "https://fast.etrackings.com/courier/fed-ex.png",
  },
  {
    key: "quantium-solutions",
    name: "ควอนเธียม โซลูชั่นส์",
    color: "#14D250",
    imageURL: "https://fast.etrackings.com/courier/quantium-solutions.png",
  },
  {
    key: "shippop",
    name: "ชิปป๊อป",
    color: "#07A5DC",
    imageURL: "https://fast.etrackings.com/courier/shippop.jpg",
  },
  {
    key: "japan-post",
    name: "เจแปน โพสต์",
    color: "#DC0025",
    imageURL: "https://fast.etrackings.com/courier/japan-post.png",
  },
  {
    key: "tp-logistics",
    name: "ทีพี โลจิสติกส์",
    color: "#1AC662",
    imageURL: "https://fast.etrackings.com/courier/tp-logistics.png",
  },
  {
    key: "bs-express",
    name: "บี.เอส เอ็กซ์เพรส",
    color: "#FACF24",
    imageURL: "https://fast.etrackings.com/courier/bs-express.jpg",
  },
  {
    key: "dpx-logistics",
    name: "ดีพีเอ็กซ์ โลจิสติกส์",
    color: "#20B1FE",
    imageURL: "https://fast.etrackings.com/courier/dpx-logistics.png",
  },
  {
    key: "blue-white-express",
    name: "บลู แอนด์ ไวท์ เอ็กซ์เพรส",
    color: "#1CA2FF",
    imageURL: "https://fast.etrackings.com/courier/blue-white-express.png",
  },
  {
    key: "sky-box",
    name: "สกายบอกซ์",
    color: "#2277D6",
    imageURL: "https://fast.etrackings.com/courier/sky-box.jpg",
  },
  {
    key: "dhl-bulky",
    name: "ดีเอชแอล Bulky",
    color: "#F5BA02",
    imageURL: "https://fast.etrackings.com/courier/dhl-bulky.png",
  },
  {
    key: "it-transport",
    name: "ไอที ทรานสปอร์ต",
    color: "#F97723",
    imageURL: "https://fast.etrackings.com/courier/it-transport.png",
  },
  {
    key: "korea-post",
    name: "ไปรษณีย์สาธารณรัฐเกาหลี",
    color: "#DE0000",
    imageURL: "https://fast.etrackings.com/courier/korea-post.png",
  },
  {
    key: "tnt-express",
    name: "ทีเอ็นที เอ็กซเพรส",
    color: "#F96124",
    imageURL: "https://fast.etrackings.com/courier/tnt-express.png",
  },
  {
    key: "send-it",
    name: "เซ็นด์อิท",
    color: "#FFA21C",
    imageURL: "https://fast.etrackings.com/courier/send-it.png",
  },
  {
    key: "logistics-worldwide-express",
    name: "Logistics Worldwide Express",
    color: "#00CD5D",
    imageURL:
      "https://fast.etrackings.com/courier/logistics-worldwide-express.png",
  },
  {
    key: "southern-delivery-service",
    name: "เซ้าท์เทิร์น เดลิเวอรี่ เซอร์วิส",
    color: "#0B6FF7",
    imageURL:
      "https://fast.etrackings.com/courier/southern-delivery-service.png",
  },
  {
    key: "ecms-express",
    name: "ECMS Express",
    color: "#0CCE5E",
    imageURL: "https://fast.etrackings.com/courier/ecms-express.png",
  },
  {
    key: "jwd-express",
    name: "เจดับเบิ้ลยูดี เอ็กซ์เพรส",
    color: "#00D5D8",
    imageURL: "https://fast.etrackings.com/courier/jwd-express.jpg",
  },
  {
    key: "cambodia-post",
    name: "ไปรษณีย์กัมพูชา",
    color: "#0094DE",
    imageURL: "https://fast.etrackings.com/courier/cambodia-post.png",
  },
  {
    key: "dsv",
    name: "ดีเอสวี",
    color: "#003490",
    imageURL: "https://fast.etrackings.com/courier/dsv.png",
  },
  {
    key: "ntc-express",
    name: "เอ็นทีซี เอ็กซ์เพรส",
    color: "#0E77FE",
    imageURL: "https://fast.etrackings.com/courier/ntc-express.png",
  },
  {
    key: "hermes-world",
    name: "Hermes World",
    color: "#11B6F4",
    imageURL: "https://fast.etrackings.com/courier/hermes-world.png",
  },
  {
    key: "sme-shipping",
    name: "เอสเอ็มอี ชิปปิ้ง",
    color: "#FF643A",
    imageURL: "https://fast.etrackings.com/courier/sme-shipping.jpg",
  },
  {
    key: "nakhonchai-air",
    name: "นครชัยแอร์",
    color: "#3690F6",
    imageURL: "https://fast.etrackings.com/courier/nakhonchai-air.png",
  },
  {
    key: "canada-post",
    name: "ไปรษณีย์แคนาดา",
    color: "#2360EB",
    imageURL: "https://fast.etrackings.com/courier/canada-post.png",
  },
  {
    key: "yusen-logistics",
    name: "ยูเซ็น โลจิสติกส์",
    color: "#11EDF4",
    imageURL: "https://fast.etrackings.com/courier/yusen-logistics.png",
  },
  {
    key: "spee-dee-delivery",
    name: "Spee-Dee Delivery",
    color: "#FF4610",
    imageURL: "https://fast.etrackings.com/courier/spee-dee-delivery.png",
  },
  {
    key: "usps",
    name: "ไปรษณีย์สหรัฐ",
    color: "#9E7BDF",
    imageURL: "https://fast.etrackings.com/courier/usps.png",
  },
  {
    key: "landmark-global",
    name: "Landmark Global",
    color: "#D1002C",
    imageURL: "https://fast.etrackings.com/courier/landmark-global.png",
  },
  {
    key: "phl-post",
    name: "ไปรษณีย์ฟิลิปปินส์",
    color: "#064DCC",
    imageURL: "https://fast.etrackings.com/courier/phl-post.png",
  },
  {
    key: "db-schenker",
    name: "ดีบี เชงเกอร์",
    color: "#F7111F",
    imageURL: "https://fast.etrackings.com/courier/db-schenker.png",
  },
  {
    key: "shipjung",
    name: "ชิปจัง",
    color: "#FA8A12",
    imageURL: "https://fast.etrackings.com/courier/shipjung.png",
  },
  {
    key: "ctt-express",
    name: "ซีทีที เอ็กซ์เพรส",
    color: "#2B7DFA",
    imageURL: "https://fast.etrackings.com/courier/ctt-express.png",
  },
  {
    key: "dpd",
    name: "DPD",
    color: "#DE002F",
    imageURL: "https://fast.etrackings.com/courier/dpd.png",
  },
  {
    key: "chronopost",
    name: "โครโนโพสต์",
    color: "#13C0EF",
    imageURL: "https://fast.etrackings.com/courier/chronopost.jpeg",
  },
  {
    key: "city-link-express",
    name: "City-Link Express",
    color: "#13D339",
    imageURL: "https://fast.etrackings.com/courier/city-link-express.png",
  },
  {
    key: "book-my-cargo",
    name: "บุ๊คมายคาร์โก",
    color: "#FF7718",
    imageURL: "https://fast.etrackings.com/courier/book-my-cargo.jpg",
  },
  {
    key: "sabina",
    name: "ซาบีน่า",
    color: "#7742FA",
    imageURL: "https://fast.etrackings.com/courier/sabina.png",
  },
];
